const products = [
  {
    title: "Magnetite",
    category: ['Rock'],
    price: 89.0,
    img: "../../assets/img/1.jpg",
    band: "Scalene",
    year: 2017,
    id: 0,
  },
  {
    title: "Acabou o Chorare",
    category: ['MPB'],
    price: 66.0,
    img: "../../assets/img/2.jpg",
    band: "Novos Baianos",
    year: 1972,
    id: 1,
  },
  {
    title: "Nirvana Discografia",
    category: ['Rock'],
    price: 50.0,
    img: "../../assets/img/3.jpg",
    band: "Nirvana",
    year: 1990,
    id: 2,
  },
  {
    title: "Both Sides",
    category: ['Pop'],
    price: 22.0,
    img: "../../assets/img/4.jpg",
    band: "Phil Collins",
    year: 1993,
    id: 3,
  },
  {
    title: "Led Zeppelin IV",
    category: ['Rock'],
    price: 19.0,
    img: "../../assets/img/5.png",
    band: "Led Zeppelin",
    year: 1970,
    id: 4,
  },
  {
    title: "Luiz Lua Gonzaga",
    category: ['Baião'],
    price: 12.0,
    img: "../../assets/img/6.jpeg",
    band: "Luiz Gonzaga",
    year: 1960,
    id: 5,
  },
  {
    title: "Don't Call Me Marshall",
    category: ['Rap'],
    price: 34.0,
    img: "../../assets/img/7.webp",
    band: "Luiz Gonzaga",
    year: 2003,
    id: 6,
  },
];

const categories = [
  "Todos",
  "Pop",
  "MPB",
  "Forró",
  "Samba",
  "Baião",
  "Rap",
  "Hip-Hop",
  "Rock",
  "Reggae",
  "Country",
  "Gospel",
];